---
- name: Deploy FastAPI ANPR Application
  hosts: azure_vms
  gather_facts: true
  
  vars:
    app_dir: /home/ubuntu/repos/fastapi-anpr
    github_user: micrometre
    docker_compose_version: "2.24.0"
  
  tasks:

    - name: Clean up existing directory if it exists
      file:
        path: "{{ app_dir }}"
        state: absent
      
    - name: Create required directories
      file:
        path: "/home/ubuntu/{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
      become_user: "{{ ansible_user }}"
      loop:
        - repos

    - name: Accept GitHub host key
      shell: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      become_user: "{{ ansible_user }}"
      
    - name: Clone application repository
      git:
        repo: git@github.com:{{github_user}}/fastapi-anpr.git
        dest: "{{ app_dir }}"
        version: azure
        accept_hostkey: yes
      become_user: "{{ ansible_user }}"

    # name: Start application
    # shell: make start-domain
    # args:
    #   chdir: "{{ app_dir }}"
    # become_user: "{{ ansible_user }}"

    - name: Display application URL
      debug:
        msg: |
          ========================================
          Application Deployed Successfully!
          ========================================
          Access the application at:
          https://{{ ansible_host }}
          ========================================
